#!/bin/sh

I=$(cat <<EOF
import org.scalacheck.Prop._
import cats._
import cats.effect._
import fs2._
import fs2.io.file._

import cats.effect.unsafe.implicits.global

import spire._
import spire.math._
import spire.implicits._
EOF
)

scala-cli repl \
	-S 3.8.3 \
	--toolkit typelevel:default \
 	--dep "org.scalacheck::scalacheck:1.19.0" \
 	--dep "org.typelevel::spire:0.18.0" \
	--repl-init-script "$I"
