#!/usr/bin/env python3
import os
import sys

from wayfire_socket import *

s = WayfireSocket(os.getenv("WAYFIRE_SOCKET"))

msg = ""

match sys.argv[1]:
    case "expo":
        msg = get_msg_template("expo/toggle")
    case "scale":
        msg = get_msg_template("scale/toggle")

s.send_json(msg)
